# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from Protos import card_recharge_pb2 as Protos_dot_card__recharge__pb2


class CardRechargeStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RequestRechargeUnary = channel.unary_unary(
                '/operations.CardRecharge/RequestRechargeUnary',
                request_serializer=Protos_dot_card__recharge__pb2.CardRechargeRequest.SerializeToString,
                response_deserializer=Protos_dot_card__recharge__pb2.CardRechargeReply.FromString,
                )
        self.RequestRechargeStream = channel.stream_stream(
                '/operations.CardRecharge/RequestRechargeStream',
                request_serializer=Protos_dot_card__recharge__pb2.CardRechargeRequest.SerializeToString,
                response_deserializer=Protos_dot_card__recharge__pb2.CardRechargeReply.FromString,
                )


class CardRechargeServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RequestRechargeUnary(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RequestRechargeStream(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CardRechargeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RequestRechargeUnary': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestRechargeUnary,
                    request_deserializer=Protos_dot_card__recharge__pb2.CardRechargeRequest.FromString,
                    response_serializer=Protos_dot_card__recharge__pb2.CardRechargeReply.SerializeToString,
            ),
            'RequestRechargeStream': grpc.stream_stream_rpc_method_handler(
                    servicer.RequestRechargeStream,
                    request_deserializer=Protos_dot_card__recharge__pb2.CardRechargeRequest.FromString,
                    response_serializer=Protos_dot_card__recharge__pb2.CardRechargeReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'operations.CardRecharge', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class CardRecharge(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RequestRechargeUnary(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/operations.CardRecharge/RequestRechargeUnary',
            Protos_dot_card__recharge__pb2.CardRechargeRequest.SerializeToString,
            Protos_dot_card__recharge__pb2.CardRechargeReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RequestRechargeStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/operations.CardRecharge/RequestRechargeStream',
            Protos_dot_card__recharge__pb2.CardRechargeRequest.SerializeToString,
            Protos_dot_card__recharge__pb2.CardRechargeReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
